#!/usr/bin/env python
"""Record the Python half of ``suites/provider-rate-limits/cases.json``.

The reference's half is generated by ``tools/generate-provider-rate-limits.php``
and the TypeScript half by ``tools/record-provider-rate-limits.mjs``. This suite
is a ``security-corpus``, so there is no ``expect`` to compare against: each row
records what every language PRODUCED and the three answers are the finding. That
only means anything if every column was EXECUTED, so this runs the port rather
than transcribing a reading of its source.

::

    python tools/record_provider_rate_limits.py
    python tools/record_provider_rate_limits.py --check

It imports prism-py from the sibling checkout in the ``.agi`` envelope, the same
way the PHP generator reaches for the reference's autoloader. That is a
GENERATOR's licence and not a loader's -- loaders must find fixtures inside their
own published artifact, and nothing here is shipped. ``PRISM_PY_SRC`` overrides
the location.
"""

from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

ROOT = Path(__file__).resolve().parent.parent
SRC = Path(os.environ.get("PRISM_PY_SRC") or ROOT.parent / "prism-py" / "src").resolve()

if not (SRC / "prism" / "__init__.py").is_file():
    print(f"No prism-py source at {SRC}. Set PRISM_PY_SRC.", file=sys.stderr)
    raise SystemExit(3)

sys.path.insert(0, str(SRC))

from prism.providers.anthropic.rate_limits import (  # noqa: E402
    parse_rate_limits as anthropic_limits,
)
from prism.providers.mistral.rate_limits import (  # noqa: E402
    parse_rate_limits as mistral_limits,
)
from prism.providers.openai.rate_limits import parse_rate_limits as openai_limits  # noqa: E402
from prism.value_objects import ProviderRateLimit  # noqa: E402

Reader = Callable[..., "list[ProviderRateLimit]"]

#: Anthropic's reset is an INSTANT and takes no clock; the other two are
#: durations and take one. That asymmetry is the port's, not this file's -- it is
#: why the two duration readers accept an injectable ``now`` at all.
READERS: dict[str, Reader] = {
    "anthropic": anthropic_limits,
    "mistral": mistral_limits,
    "openai": openai_limits,
}


def run(case: dict[str, Any]) -> dict[str, Any]:
    given = case["given"]
    provider = given["provider"]
    now = datetime.fromtimestamp(given["now"], tz=timezone.utc)

    try:
        # Header names are handed over EXACTLY as the row wrote them, case
        # included. Lower-casing here would answer prl-0008 in this file instead
        # of in the port, which is the row about a title-casing proxy.
        limits = (
            READERS[provider](given["headers"])
            if provider == "anthropic"
            else READERS[provider](given["headers"], now=now)
        )
    except Exception:  # noqa: BLE001 - the fact that it raised is the record
        return {"outcome": "raised", "buckets": None}

    return {"outcome": "ok", "buckets": [limit.to_dict() for limit in limits]}


def main() -> int:
    check = "--check" in sys.argv
    path = ROOT / "suites" / "provider-rate-limits" / "cases.json"
    document = json.loads(path.read_text(encoding="utf-8"))
    stale: list[str] = []

    for case in document["cases"]:
        produced = run(case)
        recorded = case["result"].get("py")

        if recorded != produced:
            stale.append(
                f"{case['id']}: recorded {json.dumps(recorded)}, "
                f"prism-py produces {json.dumps(produced)}"
            )

        case["result"]["py"] = produced

    # Derived from whichever columns exist, never asserted. A row cannot be
    # marked as agreeing by an editor who wanted it to.
    for case in document["cases"]:
        answers = [answer for answer in case["result"].values() if answer is not None]
        case["agrees"] = len(answers) > 1 and len({json.dumps(a) for a in answers}) == 1

    if check:
        if stale:
            print(
                "Stale Python rows in provider-rate-limits:\n  " + "\n  ".join(stale),
                file=sys.stderr,
            )
            return 1

        print("provider-rate-limits: every Python row matches prism-py.", file=sys.stderr)
        return 0

    path.write_text(json.dumps(document, indent=4, ensure_ascii=False) + "\n", encoding="utf-8")
    print(
        "provider-rate-limits: no change."
        if not stale
        else f"provider-rate-limits: rewrote {len(stale)} Python row(s).",
        file=sys.stderr,
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
