#!/usr/bin/env python
"""Record the Python half of ``suites/opentelemetry-span-attributes/cases.json``.

The reference's half is generated by ``tools/generate-otel-span-attributes.php``
and the TypeScript half by ``tools/record-otel-span-attributes.mjs``. This suite
is a ``security-corpus``, so there is no ``expect`` to compare against: each row
records what every language PRODUCED and the three answers are the finding. That
only means anything if every column was EXECUTED, so this runs the port rather
than transcribing a reading of its source.

::

    python tools/record_otel_span_attributes.py
    python tools/record_otel_span_attributes.py --check

WHY THIS DID NOT EXIST UNTIL NOW, and what its absence cost. The suite had a PHP
generator and no recorder for the other two columns, so a new row's ``ts`` and
``py`` spans had to be written BY HAND -- producing a corpus that asserts what
its author believed the ports do. Registered as G-62.

The cost was not hypothetical. ``AdvertisedTool``'s digest shipped in
particle-academy/prism v0.124.0 hashing an empty parameter map as ``[]``, a
PHP-ism no other language reproduces, so the attribute that exists to be
compared ACROSS services was not comparable across services. Every test asserted
PHP against PHP and the release audit asked a different question. It surfaced
while these recorders were being written, before a line of them ran.

It imports the port from the sibling checkout in the ``.agi`` envelope, the same
way the PHP generator reaches for the reference's autoloader. That is a
GENERATOR's licence and not a loader's -- loaders must find fixtures inside their
own published artifact, and nothing here is shipped. ``PRISM_OTEL_PY_SRC``
overrides the location.
"""

from __future__ import annotations

import json
import os
import sys
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
SRC = Path(
    os.environ.get("PRISM_OTEL_PY_SRC") or ROOT.parent / "prism-opentelemetry-py" / "src"
).resolve()

if not (SRC / "prism_opentelemetry" / "__init__.py").is_file():
    print(f"No prism-opentelemetry-py source at {SRC}. Set PRISM_OTEL_PY_SRC.", file=sys.stderr)
    raise SystemExit(3)

sys.path.insert(0, str(SRC))

import prism_opentelemetry as port  # noqa: E402
from prism_opentelemetry import (  # noqa: E402
    GenerationContext,
    RateLimit,
    SpanStore,
    TelemetrySubscriber,
    Usage,
)

#: The port's own digest helper, or None.
#:
#: Read off the module rather than reimplemented here. A recorder that computed
#: the digest itself would record agreement between THIS FILE and the reference
#: while the port computed something else entirely -- the vacuous-pass shape this
#: repository exists to prevent. If the port exports no helper, the column
#: records the absence, the row disagrees, and that is the honest answer.
advertised_tool_digest = getattr(port, "advertised_tool_digest", None)

AdvertisedTool = getattr(port, "AdvertisedTool", None)


@dataclass
class RecordedSpan:
    name: str
    status: str = "unset"
    attributes: dict[str, Any] = field(default_factory=dict)

    def set_attribute(self, key: str, value: Any) -> None:
        self.attributes[key] = value

    def set_status(self, code: str, message: str | None = None) -> None:
        self.status = code

    def record_exception(self, error: BaseException) -> None:
        pass

    def end(self, end_time_nanos: int | None = None) -> None:
        pass


@dataclass
class RecordingTracer:
    """A tracer that records rather than exports -- no SDK, no collector, no clock."""

    spans: list[RecordedSpan] = field(default_factory=list)

    def start_span(
        self,
        name: str,
        start_time_nanos: int | None = None,
        parent: Any = None,
    ) -> RecordedSpan:
        span = RecordedSpan(name)
        self.spans.append(span)

        return span


def advertised(tool: dict[str, Any]) -> Any:
    """A corpus tool as the port takes one.

    THE DIGEST IS COMPUTED, NOT COPIED. A row supplies the tool's DECLARATION and
    each language fingerprints it, which is the only way the corpus can ask
    whether three languages agree about the digest -- the question the attribute
    exists for. Handing every column the same precomputed string would pin the
    fixture instead of the code.
    """
    digest = (
        advertised_tool_digest(
            name=tool["name"],
            description=tool.get("description") or "",
            parameters=tool.get("parameters") or {},
        )
        if callable(advertised_tool_digest)
        else None
    )

    assert AdvertisedTool is not None, "the port exports no AdvertisedTool"

    return AdvertisedTool(
        name=tool["name"],
        digest=digest,
        description=tool.get("description"),
        parameters=tool.get("parameters"),
    )


def usage_of(entry: dict[str, Any]) -> Usage:
    """The cache and reasoning fields are optional in the fixture.

    Rows that predate them do not carry the keys, and None is how the port is
    told a provider reported nothing -- which is NOT the same as zero.
    """
    return Usage(
        prompt_tokens=entry["prompt_tokens"],
        completion_tokens=entry["completion_tokens"],
        cache_read_input_tokens=entry.get("cache_read_input_tokens"),
        cache_write_input_tokens=entry.get("cache_write_input_tokens"),
        thought_tokens=entry.get("thought_tokens"),
        cost=entry["cost"],
    )


def rate_limit_of(entry: dict[str, Any]) -> RateLimit:
    """`resets_at` is parsed HERE and not in the port.

    The port is handed an instant, so nothing in this comparison depends on three
    languages agreeing about how to render or re-render a date.
    """
    return RateLimit(
        name=entry["name"],
        limit=entry["limit"],
        remaining=entry["remaining"],
        resets_at=(
            None if entry["resets_at"] is None else datetime.fromisoformat(entry["resets_at"])
        ),
    )


def record(entry: dict[str, Any]) -> dict[str, Any]:
    g = entry["generation"]
    tracer = RecordingTracer()

    subscriber = TelemetrySubscriber(
        tracer,
        SpanStore(),
        max_content_length=entry["max_content_length"],
        capture_content=entry["capture_content"],
        now=lambda: 0,
    )

    # Absent stays absent: a row with no `tools` key must produce a span with no
    # tool attributes, which is a different assertion from a row with an empty
    # list.
    tools = g.get("tools")

    subscriber.on_generation_started(
        GenerationContext(
            trace_id=entry["id"],
            operation=g["operation"],
            provider=g["provider"],
            model=g["model"],
            session_id=g["session_id"],
            user_id=g["user_id"],
        ),
        g["input"],
        None if tools is None else [advertised(tool) for tool in tools],
    )

    subscriber.on_generation_completed(
        entry["id"],
        finish_reason=g["finish_reason"],
        usage=None if g["usage"] is None else usage_of(g["usage"]),
        output=g["output"],
        rate_limits=(
            None if g["rate_limits"] is None else [rate_limit_of(r) for r in g["rate_limits"]]
        ),
    )

    assert len(tracer.spans) == 1, f"{entry['id']}: expected exactly one root span"
    span = tracer.spans[0]

    return {
        "name": span.name,
        "status": span.status,
        "attributes": dict(sorted(span.attributes.items())),
    }


def differences(reference: dict[str, Any], other: dict[str, Any]) -> list[str]:
    """Where two recorded spans differ, by field name.

    Attribute KEYS present in one column and absent in the other count, which is
    the case that matters most here: a port emitting no digest at all is a
    disagreement, and a comparison that only looked at shared keys would call it
    agreement.
    """
    fields: list[str] = []

    if reference["name"] != other["name"]:
        fields.append("span name")

    if reference["status"] != other["status"]:
        fields.append("span status")

    keys = set(reference["attributes"]) | set(other["attributes"])

    for key in sorted(keys):
        if reference["attributes"].get(key) != other["attributes"].get(key):
            fields.append(key)

    return fields


def main() -> int:
    check = "--check" in sys.argv
    path = ROOT / "suites" / "opentelemetry-span-attributes" / "cases.json"
    document = json.loads(path.read_text(encoding="utf-8"))
    stale: list[str] = []

    for entry in document["cases"]:
        produced = record(entry)
        recorded = entry["spans"].get("py")

        if recorded != produced:
            stale.append(
                f"{entry['id']}: recorded {json.dumps(recorded)}, "
                f"prism-opentelemetry-py produces {json.dumps(produced)}"
            )

        entry["spans"]["py"] = produced

    # DERIVED from whichever columns exist, never asserted. A row cannot be
    # marked as agreeing by an editor who wanted it to, and `disagrees_on`
    # cannot quietly omit a field that started differing -- each runner asserts
    # that nothing outside the register's named set appears in it, so a new
    # divergence fails a test instead of joining a row that was already red.
    for entry in document["cases"]:
        reference = entry["spans"].get("php")
        others = [span for lang, span in entry["spans"].items() if lang != "php" and span]

        if not reference or not others:
            entry["agrees"] = False
            continue

        fields: set[str] = set()

        for span in others:
            fields.update(differences(reference, span))

        entry["agrees"] = not fields
        entry["disagrees_on"] = sorted(fields)

    if check:
        if stale:
            print(
                "Stale Python spans in opentelemetry-span-attributes:\n  " + "\n  ".join(stale),
                file=sys.stderr,
            )
            return 1

        print(
            "opentelemetry-span-attributes: every Python row matches the port.",
            file=sys.stderr,
        )
        return 0

    # newline="\n" EXPLICITLY. Python translates "\n" to the platform ending on
    # write, so on Windows this file would land CRLF while the PHP generator and
    # the TypeScript recorder write LF -- and the three tools would rewrite every
    # line of the corpus each time they ran, in turn, forever.
    path.write_text(
        json.dumps(document, indent=4, ensure_ascii=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(
        "opentelemetry-span-attributes: no change."
        if not stale
        else f"opentelemetry-span-attributes: rewrote {len(stale)} Python row(s).",
        file=sys.stderr,
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
